### PR TITLE
added compact format

### PR DESCRIPTION
**Pull request by nopeslide**

### CODE REVIEW

**Comment by nopeslide** [comment]
I added a compact mode for  multilane diagrams, resembling packet diagrams.

image

**Comment by nopeslide** [comment]
Could I get any feedback what is missing for this PR to be accepted?

**Comment by drom** [comment]
Thank you for your contribution. Everything looks great. Merging!

**Comment by drom** [comment]
https://github.com/drom/bitfield/issues/25

**Pull request merged**
