### PR TITLE
Promote fs-extra, onml, and yargs to dependencies

### PR DESCRIPTION
**Pull request by mx-shift**
In a clean NPM environemnt, npm i bit-field yields a bitfield that fails
to run.  fs-extra, onml, and yargs are required for execution but are
listed only as devDepdencies.  Promoting them to dependencies ensures
they are installed when bit-field is installed.

Signed-off-by: Rick Altherr <kc8apf@kc8apf.net>

### CODE REVIEW

**Comment by drom** [comment]
Yes, you are right. It is broken this way.
How about I include browserify step and distribute bundled version of `bin/bitfield.js` ?

**Comment by mx-shift** [comment]
Personally I prefer to use NPM.  Even if you choose to primarily distribute a bundled version, having the NPM dependencies work properly is important for anyone wanting to use it in their own project.

**Comment by drom** [comment]
Sounds fine to me!

**Comment by drom** [comment]
Just published v0.6.0

**Pull request merged**
